name: SCP private-server.pem to Public EC2

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  scp-pem:
    runs-on: ubuntu-latest
    environment: public-server.pem

    steps:
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          printf '%s\n' "${{ secrets.PUBLIC_SERVER }}" > public-server.pem
          chmod 600 public-server.pem

          printf '%s\n' "${{ secrets.PRIVATE_SERVER }}" > private-server.pem
          chmod 600 private-server.pem

          ssh-keygen -l -f public-server.pem

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ec2-44-220-83-30.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Remove old file on EC2 if exists
        run: |
          ssh -i public-server.pem ec2-user@ec2-44-220-83-30.compute-1.amazonaws.com "rm -f ~/private-server.pem"

      - name: SCP private-server.pem to EC2
        run: |
          scp -i public-server.pem private-server.pem ec2-user@ec2-44-220-83-30.compute-1.amazonaws.com:~/

      - name: Verify file copied
        run: |
          ssh -i public-server.pem ec2-user@ec2-44-220-83-30.compute-1.amazonaws.com "ls -la ~/private-server.pem"